#访问端口
server:
  port: 7002
  servlet:
    context-path:

spring:
  application:
    name: eureka #实现高可用，多个eureka应用名要相同

eureka:
  instance:
    hostname: eureka2
  #    hostname: ${spring.cloud.client.ipAddress}
  #    prefer-ip-address: true
  server:
    #    eviction-interval-timer-in-ms: 7000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: true #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:jogjo@eureka1:7001/eureka,http://admin:jogjo@eureka4:7004/eureka
#      defaultZone: http://admin:jogjo@localhost:7001/eureka